// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://www.libraryapi.com/support",
            "email": "support@libraryapi.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "Возвращает полный список книг в коллекции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Получить все книги",
                "responses": {
                    "200": {
                        "description": "Список всех книг",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.BookModel"
                            }
                        }
                    }
                }
            }
        },
        "/books/add": {
            "post": {
                "description": "Создает новую книгу с указанными параметрами",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Добавить новую книгу",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Война и мир\"",
                        "description": "Название книги",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"Лев Толстой\"",
                        "description": "Автор книги",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 599.99,
                        "description": "Цена книги",
                        "name": "price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book added successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/update": {
            "post": {
                "description": "Обновляет данные книги по её идентификатору",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Обновить книгу",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID книги для обновления",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"Обновленное название\"",
                        "description": "Новое название книги",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "\"Новый автор\"",
                        "description": "Новый автор",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "example": 699.99,
                        "description": "Новая цена",
                        "name": "price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "Возвращает детальную информацию о книге по её идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Получить книгу по ID",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID книги",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о книге",
                        "schema": {
                            "$ref": "#/definitions/model.BookModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет книгу по указанному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Удалить книгу",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID книги для удаления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book removed successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/story": {
            "get": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            },
            "post": {
                "description": "Создает новую запись о покупке или аренде книги пользователем",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Добавить новую покупку/аренду",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID книги",
                        "name": "book_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loan succesfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/story/book/{id}": {
            "get": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            },
            "delete": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            }
        },
        "/story/endpurchase/{id}": {
            "put": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            }
        },
        "/story/id/{id}": {
            "get": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            },
            "delete": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            }
        },
        "/story/update/{id}": {
            "put": {
                "description": "Обновляет данные существующей записи о покупке или аренде",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Обновить информацию о покупке",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID записи о покупке",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 2,
                        "description": "Новый ID книги",
                        "name": "book_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 3,
                        "description": "Новый ID пользователя",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loan succesfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/story/user/{id}": {
            "get": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            },
            "delete": {
                "description": "Маршрутизирует запросы к соответствующим методам обработки истории покупок",
                "summary": "Основной обработчик запросов истории покупок",
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Возвращает полный список всех пользователей в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "Список всех пользователей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        },
        "/users/add": {
            "post": {
                "description": "Создает нового пользователя в системе",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Добавить нового пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Алексей\"",
                        "description": "Имя пользователя",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"Петров\"",
                        "description": "Фамилия пользователя",
                        "name": "surname",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added successfully!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка добавления",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/update": {
            "post": {
                "description": "Обновляет данные существующего пользователя",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить пользователя",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя для обновления",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"Иван\"",
                        "description": "Новое имя пользователя",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "\"Иванов\"",
                        "description": "Новая фамилия пользователя",
                        "name": "surname",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверные данные запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка обновления",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Возвращает детальную информацию о пользователе по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет пользователя из системы по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID пользователя для удаления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User removed successfully!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка удаления",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BookModel": {
            "description": "Информация о книге",
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key Authentication",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Library Management REST API",
	Description:      "Полное REST API для управления библиотекой с поддержкой версий v1 и v2",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
